export const REF = {
  "typeFlux": [
    "PRODUITS",
    "CHARGES"
  ],
  "cat1ByType": {
    "PRODUITS": [
      "CA"
    ],
    "CHARGES": [
      "CF",
      "CV"
    ]
  },
  "cat2": {
    "PRODUITS||CA": [
      "ADHESION",
      "ASSURANCE",
      "BAPTEMES",
      "FORMATION",
      "LICENCE",
      "REPAS",
      "SORTIE EXPLO",
      "SORTIE TEK",
      "VOYAGE",
      "WIP",
      "TEXTILES, GOODIES",
      "DONS",
      "REMBOURSEMENT",
      "INTERET",
      "EPARGNE"
    ],
    "CHARGES||CF": [
      "MAINTENANCE",
      "MATERIEL",
      "ASSURANCE",
      "AG",
      "MARKETING",
      "SITE INTERNET",
      "BUREAU",
      "FRAIS",
      "FRAIS ANCV",
      "FRAIS BANCAIRE",
      "FRAIS DIVERS",
      "COTISATION CODEP",
      "COTISATION COREG",
      "COTISATION FFESSM",
      "TAXES"
    ],
    "CHARGES||CV": [
      "ALLINCL",
      "FORMATION",
      "LICENCE",
      "PLONGEES",
      "LOGEMENT",
      "ASSURANCE",
      "MARKETING",
      "REPAS",
      "TRANSPORT",
      "FRAIS ANCV",
      "FRAIS DIVERS",
      "EPARGNE"
    ]
  },
  "compte": {
    "PRODUITS||CA||ADHESION": "706 - Prestations de services",
    "PRODUITS||CA||ASSURANCE": "706 - Prestations de services",
    "PRODUITS||CA||BAPTEMES": "706 - Prestations de services",
    "PRODUITS||CA||FORMATION": "706 - Prestations de services",
    "PRODUITS||CA||LICENCE": "706 - Prestations de services",
    "PRODUITS||CA||REPAS": "706 - Prestations de services",
    "PRODUITS||CA||SORTIE EXPLO": "706 - Prestations de services",
    "PRODUITS||CA||SORTIE TEK": "706 - Prestations de services",
    "PRODUITS||CA||VOYAGE": "706 - Prestations de services",
    "PRODUITS||CA||WIP": "706 - Prestations de services",
    "PRODUITS||CA||TEXTILES, GOODIES": "707 - Ventes de marchandises",
    "PRODUITS||CA||DONS": "7541 - Dons manuels",
    "PRODUITS||CA||REMBOURSEMENT": "7541 - Dons manuels",
    "PRODUITS||CA||INTERET": "76 - Produits financiers",
    "PRODUITS||CA||EPARGNE": "76 - Produits financiers",
    "CHARGES||CF||MAINTENANCE": "615 - Entretien et réparation",
    "CHARGES||CF||MATERIEL": "615 - Entretien et réparation",
    "CHARGES||CF||ASSURANCE": "616 - Assurance",
    "CHARGES||CF||AG": "618 - Divers - Documentation",
    "CHARGES||CF||MARKETING": "623 - Publicité, publication",
    "CHARGES||CF||SITE INTERNET": "623 - Publicité, publication",
    "CHARGES||CF||BUREAU": "626 - Frais postaux et télécommunications",
    "CHARGES||CF||FRAIS": "627 - Services bancaires, autres",
    "CHARGES||CF||FRAIS ANCV": "627 - Services bancaires, autres",
    "CHARGES||CF||FRAIS BANCAIRE": "627 - Services bancaires, autres",
    "CHARGES||CF||FRAIS DIVERS": "627 - Services bancaires, autres",
    "CHARGES||CF||COTISATION CODEP": "628 - Divers - Cotisations",
    "CHARGES||CF||COTISATION COREG": "628 - Divers - Cotisations",
    "CHARGES||CF||COTISATION FFESSM": "628 - Divers - Cotisations",
    "CHARGES||CF||TAXES": "635 - Autres impôts et taxes",
    "CHARGES||CV||ALLINCL": "612 - Sous-traitance",
    "CHARGES||CV||FORMATION": "612 - Sous-traitance",
    "CHARGES||CV||LICENCE": "612 - Sous-traitance",
    "CHARGES||CV||PLONGEES": "612 - Sous-traitance",
    "CHARGES||CV||LOGEMENT": "613 - Locations",
    "CHARGES||CV||ASSURANCE": "616 - Assurance",
    "CHARGES||CV||MARKETING": "623 - Publicité, publication",
    "CHARGES||CV||REPAS": "625 - Déplacements, missions",
    "CHARGES||CV||TRANSPORT": "625 - Déplacements, missions",
    "CHARGES||CV||FRAIS ANCV": "627 - Services bancaires, autres",
    "CHARGES||CV||FRAIS DIVERS": "628 - Divers - Cotisations",
    "CHARGES||CV||EPARGNE": "66 - Charges financières"
  },
  "cat3": {
    "PRODUITS||ADHESION": [
      "0",
      "0+RF",
      "1",
      "1+RF",
      "2",
      "2+RF",
      "3+",
      "3+RF",
      "4+",
      "4+RF",
      "Jeune",
      "T"
    ],
    "PRODUITS||ASSURANCE": [
      "L1",
      "L1 TOP",
      "L2",
      "L2 TOP",
      "L3",
      "L3 TOP"
    ],
    "PRODUITS||LICENCE": [
      "Adulte",
      "Jeune"
    ],
    "PRODUITS||FORMATION": [
      "N1",
      "N2",
      "N3",
      "PE40",
      "RIFAP"
    ],
    "CHARGES||ASSURANCE": [
      "AVOIR",
      "L1",
      "L1 TOP",
      "L2",
      "L2 TOP",
      "L3",
      "L3 TOP",
      "Piscine",
      "RCMS"
    ],
    "CHARGES||FORMATION": [
      "E1",
      "N1",
      "N2",
      "N3",
      "N4",
      "PE40",
      "PSC",
      "RIFAP",
      "TIV"
    ],
    "CHARGES||LICENCE": [
      "Adulte",
      "Aidant Adulte",
      "Jeune"
    ],
    "PRODUITS||BAPTEMES": [
      "SESSION 051224"
    ],
    "PRODUITS||SORTIE EXPLO": [
      "?",
      "BANYULS 2026 06",
      "CERBERE 2023 05",
      "CERBERE 2024 06",
      "CERBERE 2025 05",
      "EL PORT DE LA SELVA 2023 06",
      "EL PORT DE LA SELVA 2024 05",
      "ESTARTIT 2022 10",
      "ESTARTIT 2023 10",
      "ESTARTIT 2024 10",
      "ESTARTIT 2025 10",
      "LA CIOTAT 2023 09",
      "LA CIOTAT 2024 09",
      "PALAMOS 2024 09",
      "PALAMOS 2025 06",
      "PALAMOS 2026 05"
    ],
    "PRODUITS||SORTIE TEK": [
      "BANYULS 2022 03 TEK 1",
      "BANYULS 2023 03 TEK 1",
      "BANYULS 2023 04 TEK 2",
      "BANYULS 2024 03 TEK 1",
      "BANYULS 2024 05 TEK 2",
      "BANYULS 2025 03 TEK 1",
      "BANYULS 2025 04 TEK 2",
      "BANYULS 2026 03 TEK 1",
      "BANYULS 2026 04 TEK 2",
      "FOSSES 2024",
      "FOSSES 2025",
      "RIFAP 2023 08"
    ],
    "PRODUITS||VOYAGE": [
      "AFS 2023 12",
      "BALI 2024 11",
      "DJIBOUTI 2025 11",
      "EGYPTE 2022 12",
      "MARTINIQUE 2026"
    ],
    "CHARGES||AG": [
      "AG 2023 09",
      "AG 2024 09",
      "AG 2025 09"
    ],
    "CHARGES||ALLINCL": [
      "AFS 2023 12",
      "BALI 2024 11",
      "DJIBOUTI 2025 11"
    ],
    "CHARGES||LOGEMENT": [
      "BANYULS 2022 04 TEK 2",
      "BANYULS 2023 03 TEK 1",
      "BANYULS 2023 04 TEK 2",
      "BANYULS 2024 03 TEK 1",
      "BANYULS 2024 05 TEK 2",
      "BANYULS 2025 03 TEK 1",
      "BANYULS 2025 04 TEK 2",
      "BANYULS 2026 03 TEK 1",
      "BANYULS 2026 04 TEK 2",
      "CERBERE 2023 05",
      "CERBERE 2024 06",
      "CERBERE 2025 05",
      "EL PORT DE LA SELVA 2023 06",
      "EL PORT DE LA SELVA 2024 05",
      "ESTARTIT 2023 10",
      "ESTARTIT 2024 10",
      "ESTARTIT 2025 10",
      "LA CIOTAT 2023 09",
      "MARTINIQUE 2026",
      "PALAMOS 2024 09",
      "PALAMOS 2025 06",
      "PALAMOS 2026 05"
    ],
    "CHARGES||PLONGEES": [
      "BANYULS 2023 03 TEK 1",
      "BANYULS 2023 04 TEK 2",
      "BANYULS 2024 03 TEK 1",
      "BANYULS 2024 05 TEK 2",
      "BANYULS 2025 03 TEK 1",
      "BANYULS 2025 04 TEK 2",
      "BANYULS 2026 03 TEK 1",
      "BANYULS 2026 04 TEK 2",
      "CERBERE 2023 05",
      "CERBERE 2024 06",
      "CERBERE 2025 05",
      "EL PORT DE LA SELVA 2023 06",
      "EL PORT DE LA SELVA 2024 05",
      "ESTARTIT 2023 10",
      "ESTARTIT 2024 10",
      "ESTARTIT 2025 10",
      "FOSSES 2023",
      "FOSSES 2024",
      "FOSSES 2025",
      "FOSSES 2026",
      "LA CIOTAT 2023 09",
      "MARTINIQUE 2026",
      "PALAMOS 2024 09",
      "PALAMOS 2025 06",
      "PALAMOS 2026 05"
    ],
    "CHARGES||REPAS": [
      "AFS 2023 12",
      "BANYULS 2023 03 TEK 1",
      "BANYULS 2023 04 TEK 2",
      "BANYULS 2024 03 TEK 1",
      "BANYULS 2024 05 TEK 2",
      "BANYULS 2025 03 TEK 1",
      "BANYULS 2025 04 TEK 2",
      "BANYULS 2026 03 TEK 1",
      "BANYULS 2026 04 TEK 2",
      "BANYULS 2026 06",
      "CERBERE 2023 05",
      "CERBERE 2024 06",
      "CERBERE 2025 05",
      "DJIBOUTI 2025 11",
      "EL PORT DE LA SELVA 2023 06",
      "EL PORT DE LA SELVA 2024 05",
      "ESTARTIT 2023 10",
      "PALAMOS 2024 09",
      "PALAMOS 2025 06",
      "PALAMOS 2026 05",
      "RIFAP 2023 08"
    ],
    "CHARGES||TRANSPORT": [
      "BANYULS 2023 03 TEK 1",
      "BANYULS 2023 04 TEK 2",
      "BANYULS 2024 03 TEK 1",
      "BANYULS 2024 05 TEK 2",
      "BANYULS 2025 03 TEK 1",
      "BANYULS 2025 04 TEK 2",
      "BANYULS 2026 03 TEK 1",
      "BANYULS 2026 04 TEK 2",
      "BANYULS 2026 06",
      "CERBERE 2023 05",
      "CERBERE 2024 06",
      "CERBERE 2025 05",
      "EL PORT DE LA SELVA 2023 06",
      "EL PORT DE LA SELVA 2024 05",
      "ESTARTIT 2023 10",
      "ESTARTIT 2024 10",
      "ESTARTIT 2025 10",
      "LA CIOTAT 2023 09",
      "PALAMOS 2024 09",
      "PALAMOS 2025 06"
    ],
    "PRODUITS||TEXTILES, GOODIES": [
      "BONNET",
      "CASQUETTE",
      "SOFTSHELL",
      "SWEAT",
      "T-SHIRT"
    ],
    "CHARGES||MARKETING": [
      "TEXTILES, GOODIES",
      "LOGICIELS"
    ],
    "PRODUITS||DONS": [],
    "PRODUITS||REMBOURSEMENT": [],
    "PRODUITS||WIP": [],
    "CHARGES||BUREAU": [],
    "CHARGES||COTISATION CODEP": [],
    "CHARGES||COTISATION COREG": [],
    "CHARGES||COTISATION FFESSM": [],
    "CHARGES||FRAIS": [],
    "CHARGES||FRAIS ANCV": [],
    "CHARGES||FRAIS BANCAIRE": [
      "AFS 2023 12",
      "DJIBOUTI 2025 11"
    ],
    "CHARGES||FRAIS DIVERS": [],
    "CHARGES||MAINTENANCE": [
      "REQUALIF"
    ],
    "CHARGES||MATERIEL": [],
    "CHARGES||SITE INTERNET": [],
    "CHARGES||TAXES": [],
    "CHARGES||EPARGNE": []
  },
  "adherents": [
    "ACHILLI Loris",
    "ALLASIA Isabelle",
    "ANGLADE Alexandre",
    "BASTRIOS Jean-Claude",
    "BENETTI Bernard",
    "BERGERET-CLARAC Huguette",
    "CAUET Yannick",
    "CHAMAYOU Thomas",
    "COUDERC Richard",
    "D'ARGENCE Frédéric",
    "ERIKSSON Joakim",
    "EVRAT Jérôme",
    "FABRE Olivier",
    "FOURNIE Timothée",
    "FRANCOIS Olivier",
    "FRANCOIS Valérie",
    "GHILARDI Eric",
    "GOULMY Armand",
    "GOULMY Sylvain",
    "GOURDOU Delphine",
    "HERNANDO SAN JOSE Alicia",
    "JUSTAUT Jonathan",
    "KERJEAN TRIBES Estelle",
    "KUNTZ Stéphane",
    "LAFFONT Frédéric",
    "LEPELTIER Nina",
    "LEPELTIER Nina ACC",
    "LETANG Philippe",
    "LETANG RIVET Paul",
    "LOPEZ Audrey",
    "LOPEZ Tom",
    "LOPEZ Vincent",
    "LOPEZ Zoé",
    "MALAVAL Frank",
    "MALAVAL Valérie",
    "MALRIN-FOURNOL Audrey",
    "MARICHAL Sylvie",
    "MEROUANI Jean-Marc",
    "MILLERAND Fabien",
    "MILLERAND Guy",
    "MONTAUT Françoise",
    "MORIAT Clothilde",
    "MOULY Franck",
    "NESPOULOUS Christine",
    "PAUL Olivier",
    "PETITMANGIN Mégane",
    "PIRAUD Bernard",
    "QUINSAT Marjolaine",
    "REMY Elian",
    "RODRIGUEZ Luis",
    "ROUDIER Frédéric",
    "SABELLE HERNANDO Anaïs",
    "SABELLE Mickael",
    "SAINT LAURENS Axel",
    "SARION Thibaut",
    "SAUZE Laurent",
    "SETAU Sura",
    "THEOPHILE Jean-Yves",
    "THOMAS Anthony",
    "THORET Bruno",
    "VAILLANT Patrick",
    "VIALADE Bastien",
    "VINATIER Luc",
    "VIOT Timothée"
  ],
  "natures": [
    "VRT",
    "PRLV",
    "CB",
    "ANCV",
    "EANCV",
    "HA",
    "CHQ"
  ],
  "natureLabels": {
    "VRT": "Virement",
    "PRLV": "Prélèvement",
    "CB": "Carte bancaire",
    "ANCV": "ANCV",
    "EANCV": "e-ANCV",
    "HA": "HelloAsso",
    "CHQ": "Chèque"
  }
};
